name: gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter

flutter_gen:
  output: lib/src/assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  fonts:
      output: lib/src/assets/  

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  lints: ^2.1.0
  test: ^1.24.0

flutter:
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_extralight.ttf
          weight: 400
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins_extrabold.ttf
          weight: 800    
