final class StringConstant {
  const StringConstant._();

  static const searchHintText = 'Search Super Foodo';
  static const hotspots = 'Hotspots';
  static const favourites = 'Favourites';
  static const noFavourites = 'There is no favourites';
  static const profile = 'Profile';
  static const featured = 'Featured';
  static const featureOnSuperFoodo = 'Featured on Super Foodo';
  static const deliveryFee = 'Delivery Fee';
  static const min = 'min';
  static const subTotal = 'SubTotal';
  static const goToCheckouts = 'Go to checkouts';
  static const getStarted = 'Get Started';
  static const onboardHeader1 = 'Trending Foods';
  static const onboardHeader2 = 'Fast Delivery';
  static const onboardHeader3 = 'Find Nearby Restaurants';
  static const onboardHeader4 = 'Easy Ordering';
  static const onboardContent1 = 'Lorem ipsum dolor sit amet consectetur. Ut cras pellentesque diam mauris laoreet donec a eget aliquam.';
  static const onboardContent2 = 'Lorem ipsum dolor sit amet consectetur. Ut cras pellentesque diam mauris laoreet donec a eget aliquam.';
  static const onboardContent3 = 'Lorem ipsum dolor sit amet consectetur. Ut cras pellentesque diam mauris laoreet donec a eget aliquam.';
  static const onboardContent4 = 'Lorem ipsum dolor sit amet consectetur. Ut cras pellentesque diam mauris laoreet donec a eget aliquam.';
  static const authHeader = 'Welcome to Super Foodo';
  static const authContent = 'Lorem ipsum dolor sit amet consectetur. Ut cras pellentesque';
  static const createAccount = 'Create Account';
  static const login = 'Login';
  static const signup = 'Sign Up';
  static const authTermsOfCondition = 'By Registering or Login you have agreed to these Terms and Conditions.';
  static const emailHint = 'Email';
  static const passwordHint = 'Password';
  static const confirmPasswordHint = 'Confirm Password';
  static const forgetPassword = 'Forget Password?';
  static const dontHaveAccount = "Don't have an account? Sign up";
  static const alreadyHaveAccount = 'Already have an account? Log in';
  static const signupFacebook = 'Sign Up with Facebook';
  static const signupGoogle = 'Sign Up with Google';
  static const or = 'OR';
  static const addToCart = 'Add 1 to Cart';
  static const noExtras = 'There is no extras for';
  static const comesWith = 'Comes With';
  static const cal = 'cal';

  static const passwordEmptyError = 'Password can not be empty';
  static const passwordDoesNotMatchError = 'Password does not match';
  static const signupFormError = 'Form error';
  static const emailValidError = 'Enter a valid email address';
  static const yourCards = 'Your Cards';
  static const addCard = 'Add Card';
}
